DROP DATABASE `village_green` IF EXISTS;
CREATE  DATBASE `village_green` IF NOT EXISTS;
USE `village_green`;
/*mise en place de la table pays*/

create table `pays`
(
    `pays_id`  char(2) UNSIGNED NOT NULL AUTO_INCREMENT,
    `pays_nom` varchar(50) NOT NULL,
    PRIMARY KEY (`pays_id`)
);
/* chargement des données à de la table pays*/

INSERT INTO `pays` (`pays_id`,`pays_nom`) VALUES
('AD', 'Andorre'),
('AE', 'Émirats Arabes Unis'),
('AF', 'Afghanistan'),
('AG', 'Antigua-et-Barbuda'),
('AI', 'Anguilla'),
('AL', 'Albanie'),
('AM', 'Arménie'),
('AN', 'Antilles Néerlandaises'),
('AO', 'Angola'),
('AQ', 'Antarctique'),
('AR', 'Argentine'),
('AS', 'Samoa Américaines'),
('AT', 'Autriche'),
('AU', 'Australie'),
('AW', 'Aruba'),
('AX', 'Îles Åland'),
('AZ', 'Azerbaïdjan'),
('BA', 'Bosnie-Herzégovine'),
('BB', 'Barbade'),
('BD', 'Bangladesh'),
('BE', 'Belgique'),
('BF', 'Burkina Faso'),
('BG', 'Bulgarie'),
('BH', 'Bahreïn'),
('BI', 'Burundi'),
('BJ', 'Bénin'),
('BM', 'Bermudes'),
('BN', 'Brunéi Darussalam'),
('BO', 'Bolivie'),
('BR', 'Brésil'),
('BS', 'Bahamas'),
('BT', 'Bhoutan'),
('BV', 'Île Bouvet'),
('BW', 'Botswana'),
('BY', 'Bélarus'),
('BZ', 'Belize'),
('CA', 'Canada'),
('CC', 'Îles Cocos (Keeling)'),
('CD', 'République Démocratique du Congo'),
('CF', 'République Centrafricaine'),
('CG', 'République du Congo'),
('CH', 'Suisse'),
('CI', 'Côte d\'Ivoire'),
('CK', 'Îles Cook'),
('CL', 'Chili'),
('CM', 'Cameroun'),
('CN', 'Chine'),
('CO', 'Colombie'),
('CR', 'Costa Rica'),
('CS', 'Serbie-et-Monténégro'),
('CU', 'Cuba'),
('CV', 'Cap-vert'),
('CX', 'Île Christmas'),
('CY', 'Chypre'),
('CZ', 'République Tchèque'),
('DE', 'Allemagne'),
('DJ', 'Djibouti'),
('DK', 'Danemark'),
('DM', 'Dominique'),
('DO', 'République Dominicaine'),
('DZ', 'Algérie'),
('EC', 'Équateur'),
('EE', 'Estonie'),
('EG', 'Égypte'),
('EH', 'Sahara Occidental'),
('ER', 'Érythrée'),
('ES', 'Espagne'),
('ET', 'Éthiopie'),
('FI', 'Finlande'),
('FJ', 'Fidji'),
('FK', 'Îles (malvinas) Falkland'),
('FM', 'États Fédérés de Micronésie'),
('FO', 'Îles Féroé'),
('FR', 'France'),
('GA', 'Gabon'),
('GB', 'Royaume-Uni'),
('GD', 'Grenade'),
('GE', 'Géorgie'),
('GF', 'Guyane Française'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GL', 'Groenland'),
('GM', 'Gambie'),
('GN', 'Guinée'),
('GP', 'Guadeloupe'),
('GQ', 'Guinée Équatoriale'),
('GR', 'Grèce'),
('GS', 'Géorgie du Sud et les Îles Sandwich du Sud'),
('GT', 'Guatemala'),
('GU', 'Guam'),
('GW', 'Guinée-Bissau'),
('GY', 'Guyana'),
('HK', 'Hong-Kong'),
('HM', 'Îles Heard et Mcdonald'),
('HN', 'Honduras'),
('HR', 'Croatie'),
('HT', 'Haïti'),
('HU', 'Hongrie'),
('ID', 'Indonésie'),
('IE', 'Irlande'),
('IL', 'Israël'),
('IM', 'Île de Man'),
('IN', 'Inde'),
('IO', 'Territoire Britannique de l\'Océan Indien'),
('IQ', 'Iraq'),
('IR', 'République Islamique d\'Iran'),
('IS', 'Islande'),
('IT', 'Italie'),
('JM', 'Jamaïque'),
('JO', 'Jordanie'),
('JP', 'Japon'),
('KE', 'Kenya'),
('KG', 'Kirghizistan'),
('KH', 'Cambodge'),
('KI', 'Kiribati'),
('KM', 'Comores'),
('KN', 'Saint-Kitts-et-Nevis'),
('KP', 'République Populaire Démocratique de Corée'),
('KR', 'République de Corée'),
('KW', 'Koweït'),
('KY', 'Îles Caïmanes'),
('KZ', 'Kazakhstan'),
('LA', 'République Démocratique Populaire Lao'),
('LB', 'Liban'),
('LC', 'Sainte-Lucie'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Libéria'),
('LS', 'Lesotho'),
('LT', 'Lituanie'),
('LU', 'Luxembourg'),
('LV', 'Lettonie'),
('LY', 'Jamahiriya Arabe Libyenne'),
('MA', 'Maroc'),
('MC', 'Monaco'),
('MD', 'République de Moldova'),
('MG', 'Madagascar'),
('MH', 'Îles Marshall'),
('MK', 'L\'ex-République Yougoslave de Macédoine'),
('ML', 'Mali'),
('MM', 'Myanmar'),
('MN', 'Mongolie'),
('MO', 'Macao'),
('MP', 'Îles Mariannes du Nord'),
('MQ', 'Martinique'),
('MR', 'Mauritanie'),
('MS', 'Montserrat'),
('MT', 'Malte'),
('MU', 'Maurice'),
('MV', 'Maldives'),
('MW', 'Malawi'),
('MX', 'Mexique'),
('MY', 'Malaisie'),
('MZ', 'Mozambique'),
('NA', 'Namibie'),
('NC', 'Nouvelle-Calédonie'),
('NE', 'Niger'),
('NF', 'Île Norfolk'),
('NG', 'Nigéria'),
('NI', 'Nicaragua'),
('NL', 'Pays-Bas'),
('NO', 'Norvège'),
('NP', 'Népal'),
('NR', 'Nauru'),
('NU', 'Niué'),
('NZ', 'Nouvelle-Zélande'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Pérou'),
('PF', 'Polynésie Française'),
('PG', 'Papouasie-Nouvelle-Guinée'),
('PH', 'Philippines'),
('PK', 'Pakistan'),
('PL', 'Pologne'),
('PM', 'Saint-Pierre-et-Miquelon'),
('PN', 'Pitcairn'),
('PR', 'Porto Rico'),
('PS', 'Territoire Palestinien Occupé'),
('PT', 'Portugal'),
('PW', 'Palaos'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Réunion'),
('RO', 'Roumanie'),
('RU', 'Fédération de Russie'),
('RW', 'Rwanda'),
('SA', 'Arabie Saoudite'),
('SB', 'Îles Salomon'),
('SC', 'Seychelles'),
('SD', 'Soudan'),
('SE', 'Suède'),
('SG', 'Singapour'),
('SH', 'Sainte-Hélène'),
('SI', 'Slovénie'),
('SJ', 'Svalbard etÎle Jan Mayen'),
('SK', 'Slovaquie'),
('SL', 'Sierra Leone'),
('SM', 'Saint-Marin'),
('SN', 'Sénégal'),
('SO', 'Somalie'),
('SR', 'Suriname'),
('ST', 'Sao Tomé-et-Principe'),
('SV', 'El Salvador'),
('SY', 'République Arabe Syrienne'),
('SZ', 'Swaziland'),
('TC', 'Îles Turks et Caïques'),
('TD', 'Tchad'),
('TF', 'Terres Australes Françaises'),
('TG', 'Togo'),
('TH', 'Thaïlande'),
('TJ', 'Tadjikistan'),
('TK', 'Tokelau'),
('TL', 'Timor-Leste'),
('TM', 'Turkménistan'),
('TN', 'Tunisie'),
('TO', 'Tonga'),
('TR', 'Turquie'),
('TT', 'Trinité-et-Tobago'),
('TV', 'Tuvalu'),
('TW', 'Taïwan'),
('TZ', 'République-Unie de Tanzanie'),
('UA', 'Ukraine'),
('UG', 'Ouganda'),
('UM', 'Îles Mineures Éloignées des États-Unis'),
('US', 'États-Unis'),
('UY', 'Uruguay'),
('UZ', 'Ouzbékistan'),
('VA', 'Saint-Siège (état de la Cité du Vatican)'),
('VC', 'Saint-Vincent-et-les Grenadines'),
('VE', 'Venezuela'),
('VG', 'Îles Vierges Britanniques'),
('VI', 'Îles Vierges des États-Unis'),
('VN', 'Viet Nam'),
('VU', 'Vanuatu'),
('WF', 'Wallis et Futuna'),
('WS', 'Samoa'),
('YE', 'Yémen'),
('YT', 'Mayotte'),
('ZA', 'Afrique du Sud'),
('ZM', 'Zambie'),
('ZW', 'Zimbabwe');

/* mise en place de la table poste*/

create table `postes`(
                         `pos_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                         `pos_nom` varchar(50) NOT NULL,
                         PRIMARY KEY (`pos_id`)
);

/*chargement des données à la table poste*/

insert into `postes`(`pos_id`,`pos_nom`)
values (1,`President Directeur General`),
       (2,`Directeur(/trice) des finances`),
       (3, `Directeur(/trice) des ressources humaines`),
       (4, `Directeur(/trice)commercial`),
       (5, `preparateur(trice) de commande`),
       (6, `vigile`),
       (7, `Manageur(geuse)`),
       (8, `Commercial(e)`),
       (9, `comptable`),
       (10, `Chef(fe) de rayon`),
       (11, `Technicien(/ne) support informatique`),
       (12, `Technicien(/ne) de maintenance`),
       (13, `Hote(/esse`),
       (14, `Directeur des systemes informatique`),
       (15, `Acheteur`),
       (16, `Assistant RH`);

/*création de la table departement*/

create table `departements`(
                               `dep_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                               `dep_nom` varchar(50) NOT NULL,
                               PRIMARY KEY(`dep_id`)
);

/*chargement des données à la departement*/

insert  into `departements`(`dep_id`, `dep_nom`)
value (1, `Direction`),
      (2, `Ressources humaines`),
      (3, `Logistique`),
      (4, `Direction des systémes d\'information`),
      (5, `Distribution`),
      (6, `Marketing`),
      (7, `Comptabilités`),
      (8, `Achat`);

/*création de la table employés*/

create table `employes`(
                           `emp_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                           `emp_nom` varchar (50) NOT NULL,
                           `emp_pre` varchar(50) NOT NULL,
                           `emp_genre` char(1) NOT NULL,
                           `emp_voie` varchar(50) NOT NULL,
                           `emp_nro_voie` int(10) NOT NULL,
                           `emp_codpos` int(10) NOT NULL,
                           `emp_ville` varchar(50) NOT NULL,
                           `emp_phone` int(20) NOT NULL,
                           `emp_mail` varchar(50) NOT NULL,
                           `emp_date_emb` datetime NOT NULL,
                           `emp_nbr_enf` int(10) NOT NULL,
                           `emp_sal` decimal(15.2) NOT NULL,
                           `emp_fou_id` int(10) NOT NULL,
                           `emp_pos_id` int(10) NOT NULL,
                           `emp_dep_id` int(10) NOT NULL,
                           `emp_pays_id` int(10) NOT NULL,
                           `emp_sup_id` int(10) UNSIGNED DEFAULT NULL,
                           PRIMARY KEY (`emp_id`),
                           FOREIGN KEY (`emp_fou_id`) references `fournisseurs` (`fou_id`),
                           FOREIGN KEY (`emp_pos_id`) references `postes` (`pos_id`),
                           FOREIGN KEY (`emp_dep_id`) references `departements` (`dep_id`),
                           FOREIGN KEY (`emp_sup_id`) references `employes` (`emp_id`),
                           FOREIGN KEY (`emp_pays_id`) references `pays` (`pays_id`)
);

/*chargement de données à la table employé*/

insert into `employes`(`emp_id`,`emp_pos_id`,`emp_sup_id`,`emp_dep_id`,`emp_nom`,`emp_pre`,`emp_genre`,`emp_voie`,`emp_nro_voie`,`emp_codpos`,`emp_ville`,`emp_pays_id`,`emp_phone`,`emp_mail`,`emp_date_emb`,`emp_nbr_enf`,`emp_sal`,`emp_fou_id`)
values (1,1,null,1,`DURAND`,`Georges`,`M`,`Boulevard Balzac`,10,94320,`BRY-SUR-MARNE`,`FR`,0630014277,`durandgeorges@yahoo.zp`,01/01/1999,3,20000.00,null),
       (2,9,12,7,`JEAN`,`Marinne`,`F`,`Rue Molier`,2,7700,`Villiers`,`FR`,0760023442,`jeanmarinne@hotmail.com`,01/02/2015,2,16000.00,null),
       (3,15,14,8,`SOUBALI`,`Ichame`,`M`,`Rue Balzac`,20,80000,`AMIENS`,`FR`,0700200040,`soubaliichame@y.com`,03/12/2010,1,14000.00,6),
       (4,10,14,3,`ASSILE`,`Isabelle`,`F`,`Avenue Beauville`,7,80080,`Salouël`,`FR`,0637560100,`assileisabelle@g.com`,02/07/2015,2,13000.00,1),
       (5,6,13,5,`SIMONE`,`Eric`,`M`,`Boulevard méliés`,7,85000,`Boukis`,`FR`,0434770032,`simoneeric@hot.com`,03/05/2001,2,12000.00,null),
       (6,5,14,3,`DORIAN`,`Maria`,`F`,`Rue St Georges`,2,60000,`Calan`,`FR`,0653473800,`dorienmaria@mel.com`,01/02/2000,null,13000.00,null),
       (7,13,9,5,`FILIOR`,`Sandrine`,`F`,`Avenue Mir`,10,50020,`Aniers`,`FR`,0650009001,`filiorsandrine@kal.com`,01/01/2010,2,11000.00,null),
       (8,13,9,5,`BARRY`,`Ali`,`M`,`Boulevard Charles`,19,89080,`Ain`,`FR`,0504020900,`barryali@hot.com`,02/12/2012,3,11000.00,null),
       (9,8,14,5,`SOUANE`,`Brahim`,`M`,`Rue salouel`,3,80680,`Berne`,`FR`,0600012001,`souanebrahim@gm.fr`,03/01/2000,3,14000.OO,7),
       (10,8,14,5,`BOUZA`,`Soul`,`M`,`Avenue Gorgette`,1,69000,`Villiers`,`FR`,0704569000,`bouzasoul1@ht.com`,02/01/2000,3,16000.00,5),
       (11,4,12,1,`MILLER`,`Chris`,`M`,`Impasse colin`,10,42890,`Beauchamps`,`FR`,0700049001,`millerchris@yh.com`,01/09/2003,NULL ,16000.00,null),
       (12,2,1,1,`BORNE`,`Myléne`,`F`,`Rue Beauville`,2,80080,`Salouël`,`FR`,0760017700,`bornemylene@team.com`,01/02/2001,1,16000.00,null),
       (13,3,12,1,`DARMATAN`,`Cydric`,`M`,`Bis rue collin`,3,60060,`Beauvais`,`FR`,0700012004,`darmtancydric@hot.com`,04/05/2003,null ,16000.00,null),
       (14,7,13,5,`CORNER`,`Blaise`,`M`,`Rue Mopase`,19,56030,`Toun`,`FR`,0600099000,`cornerblaise@cm.fr`,03/12/2012,3,13000.00,4),
       (15,16,3,2,`DRAKIL`,`Brems`,`M`,`Bis rue Balzac`,2,80080,`AMIENS`,`FR`,0789059023,`drakilbrems@tl.com`,03/04/2000,null ,13000.00,null),
       (16,14,3,1,`YOUSSEF`,`Karim`,`M`,`Avenue Midrette`,76,56020,`Ponin`,`FR`,0670030000,`youssefkarim@ml.fr`,09/01/2015,3,15000.00,null),
       (17,12,14,3,`WARMER`,`Elisabeth`,`F`,`Rue Moulin`,40,77800,`Pente`,`FR`,0656043423,`elisabethwarmer@cl.fr`,09/09/2006,14000.00,null),
       (18,11,16,4,`SOUM`,`Kerf`,`M`,`Rue des sourires`,3,65090,`Creil`,`FR`,0789050665,`kerfsoum20@hl.com`,09/12/2009,1,14000.00,null),
       (19,5,14,3,`DIARA`,`Souleymane`,`M`,`Boulevard st Anne`,10,80000,`Amiens`,`FR`,0706009040,`diarasouleymane@ht.com`,09/05/2019,1,13000.00,null ),
       (20,15,14,8,`SOUZA`,`Corine`,`F`,`Rue fiquet`,3,85000,`Albertville`,`FR`,0605002045,`corinesouza@yo.com`,09/12/2001,2,14000.00,4),
       (21,5,14,3,`DIBOLA`,`George`,`M`,`Rue calmette`,3,80080,`Amiens`,`FR`,0506045070,`dibolageorge@cn.fr`,09/04/2009,3,13000.00,null);




/*creation de la table client*/

create table `clients`(
                          `cli_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                          `cli_nom` varchar(50) NOT NULL,
                          `cli_pre` varchar(50) NOT NULL,
                          `cli_voie` varchar(50) NOT NULL,
                          `cli_nro_voie` int(10) NOT NULL,
                          `cli_codpos` int (20) NOT NULL,
                          `cli_ville` varchar(50) NOT NULL,
                          `cli_phone` int(20) NOT NULL,
                          `cli_mail` varchar(50) NOT NULL,
                          `cli_type` varchar(50) NOT NULL,
                          `cli_emp_id` int(10) NOT NULL,
                          `cli_pays_id` int(10) NOT NULL,
                          PRIMARY KEY (`cli_id`),
                          Foreign KEY (`cli_emp_id`) references `employes` (`emp_id`),
                          Foreign KEY (`cli_pays_id`) references `pays` (`pays_id`)
);

/*chargement des données à la table client*/

insert  into `clients`(`cli_id`, `cli_nom`, `cli_pre`, `cli_voie`, `cli_nro_voie`,`cli_codpos`,`cli_ville`, `cli_phone`, `cli_mail`, `cli_type`, `cli_emp_id`, `cli_pays_id`)
values (1,`LIGNAC`,`Gerome`,`Rue de Bastille`,2,75012,`Paris`,0606009000,`lignacgerome@ya.com`,`particulier`,14,`FR`),
       (2,`KOLON`,`Harouna`,`Rue verte`,10,1028,`Bruxelles`,00325890890003,`kolonharouna@ht.be`,`professionnel`,14,`BE`),
       (3,`SIMONE`,`Elisabeth`,`Rue Lacuée`,4,75012,`Paris`,0700012003,`simoneelisabeth@ml.fr`,`particulier`,4,`FR`),
       (4,`SOUAMAORO`,`Ismael`,`Rue Beauville`,70,80080,`Amiens`,0702009001,`soumaoroismael@ht.com`,`particulier`,4,`FR`),
       (5,`LEBLANC`,`Eric`,`Rue ain`,2,95000,`Sarcelles`,0768000900,`leblanceric@ht.com`,`professionnel`,10,`FR`),
       (6,`BEN`,`Abdel`,`Rue Magenta`,2,78020,`Limay`,0700340001,`benabdel@gm.fr`,`Professinnel`,10,`FR`),
       (7,`CARLOS`,`Roberto`,`Carrera san jeronimo`,2,28010,`Madrid`,0034567890876,`carlosroberto@ht.es`,`professionnel`,10,`ES`),
       (9,`JAILLARD`,`Benjamin`,`Rue lorene`,30,60060,`Creil`,0769009000,`jaillardbenjamin`,`particulier`,14,`FR`),
       (10,`BINETA`,`Gaoussou`,`Boulevard St Joseph`,17,76020,`Verviers`,0700010900,`binetagaoussou@ht.com`,`particuler`,4,`FR`),
       (11,`KAMEL`,`Idris`,`Rue Morceau`,2,78000,`Mantes`,0700090807,`kamelidris@hy.com`,`particulier`,14,`FR`),
       (12,`RENARD`,`Sofia`,`Avenue Goerges`,90,94000,`Créteil`,0678760004,`renardsofia@ht.com`,`particulier`,4,`FR`),
       (13,`BOURGES`,`Anne`,`Rue des clois`,3,23000,`Lima`,0700019090,`bourgesanne@hy.com`,`particulier`,10,`FR`),
       (14,`SULIMA`,`Yassine`,`Avenue Général De Gaule`,2,94020,`Boissy St Goerges`,060001200001,`sulimaneyassine@ml.fr`,`professionnel`,4,`FR`),
       (15,`KONE`,`Drissa`,`Clos chapelle-aux-champs`,2,1200,`Bruxelles`,03274909010990,`drissakone32@ht.com`,`particulier`,10,`BE`),
       (16,`CHERIF`,`Issa`,`Rue des libres`,87,69000,`Lyon`,076090050401,`issacherif@ml.com`,`professionnel`,14,`FR`),
       (17,`DURAND`,`Michel`,`Rue des bonnes nouvelles`,20,75012,`Paris`,0679096745,`micheldurand@music.fr`,`professionel`,4,`FR`);

/*création de la table fournisseur*/

create table `fournisseurs`(
                               `fou_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                               `fou_nom` varchar(50) NOT NULL,
                               `fou_voie` varchar(50) NOT NULL,
                               `fou_nro_voie` int(20) NOT NULL,
                               `fou_codpos` int(10) NOT NULL,
                               `fou_ville` varchar(50) NOT NULL,
                               `fou_phone` int(20) NOT NULL,
                               `fou_mail` varchar(50) NOT NULL,
                               `fou_type` varchar(50) NOT NULL,
                               `fou_pays_id` int(10) NOT NULL,
                               PRIMARY KEY (`fou_id`),
                               FOREIGN KEY (`fou_pays_id`) REFERENCES `pays` (`pays_id`)
);

/*chargement des données de la table fournisseurs*/

insert into `fournisseurs`(`fou_id`,`fou_nom`,`fou_voie`,`fou_nro_voie`,`fou_codpos`,`fou_ville`,`fou_phone`,`fou_mail`,`fou_type`,`fou_pays_id`)
values (1,`HEBEI`,`Boulevard Magenta`,10,75010,`Paris`,07600998900,`hebeimusic@yahoo.com`,`importateur`,`FR`),
       (2,`Music Town`,`Boulevard marchal`,10,33000,`Bordeaux`,0128674534,`musictown@ml.com`,`Fabricant`,`FR`),
       (3,`HitJazz`,`Brodway Avenue`,74,10007,`New York`,018798969575,`hitjazzprod@focus.com`,`Fabricant`,`US`),
       (4,`Found musical corporation`,`Mohrenstrasse`,2,10117,`Berlin`,0049674532343,`foundmusicalcorporation@ht.com`,`professionnel`,`DE`),
       (5,`Fender instrument`,`Jianguomenwal avenue`,1,100004,`Beijing`,0086674563920,`fenderinstrument@ht.com`,`importateur`,`CN`),
       (6,`Music flow`,`Rue volacan`,10,69000,`Lyon`,0167985603,`musicflow@gm.com`,`importateur`,`FR`),
       (7,`instrumental music`,`Rue de taverne`,23,38000,`Grenoble`,0398674527,`instrumentmusic@hotmail.com`,`importateur`,`FR`);

/*création de la table catégories*/
create table `categories`(
                             `cat_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                             `cat_nom` varchar(50) NOT NULL,
                             `cat_parent_id` int(10) UNSIGNED  DEFAULT NULL,
                             PRIMARY KEY (`cat_id`),
                             FOREIGN KEY (`cat_parent_id`) REFERENCES `categories` (`cat_id`)
);

/*chargement des données à la table categorie*/

insert into `categories`(`cat_id`,`cat_nom`,`cat_parent_id`)
values (1,`Guitare`,null ),
       (2,`Sono`,null ),
       (3,`Piano`,null ),
       (4,`Batterie`,null ),
       (5,`Micro`,null ),
       (6,`Saxo`,null ),
       (7,`Cable`,null),
       (8,`Cases`,null),
       (9,`acoustique`,1),
       (10,`classique`,1),
       (11,`éléctrique`,1),
       (12,`Amplificateur`,2),
       (13,`sonorisation portable`,2),
       (14,`lecteur audio`,2),
       (15,`acoustique`,4),
       (16,`éléctrique`,4),
       (17,`piano à queue`,3),
       (18,`piano éléctrique`,3),
       (19,`sans-fil`,5),
       (20,`micro_usb`,5),
       (21,`saxo_soprano`,6),
       (22,`saxo-baryton`,6),
       (23,`cable haut-parleur`,7),
       (24,`cable à métre`,7),
       (25,`case platine`,8),
       (26,`case contôleur dj`,8),
       (27,`case éclairage`,8);

/* création de la table produit*/

create table `produits`(
                          `pro_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                          `pro_photo` varchar(200) NOT NULL,
                          `pro_nom` varchar(50)  NOT NULL,
                          `pro_descr` varchar(80) NOT NULL,
                          `pro_pru` decimal(15,2) NOT NULL,
                          `pro_fou_id` int(10)NOT NULL,
                          `pro_cat_id` int(10) NOT NULL,
                          PRIMARY KEY (`pro_id`),
                          FOREIGN KEY (`pro_fou_id`) REFERENCES `fournisseurs` (`fou_id`),
                          FOREIGN KEY (`pro_cat_id`) REFERENCES `categories` (`cat_id`)
);

/*chargement des données à la table produit*/

insert  into `produits` (`pro_id`,`pro_photo`,`pro_nom`,`pro_descr`,`pro_pru`,`pro_fou_id`,`pro_cat_id`)
values(1,`JPG`,`guitare flok`,`Tous les modèles comprennent une table en érable, un corps en acajou massif et la touche en palissandre`,303.00,2,9),
       (2,`JPG`,`tableur`,`Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit`,507.99,5,12),
       (3,`JPG`,`Soundcraft`,`Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit`,209.00,7,27),
       (4,`JPG`,`flamenco`,`Surtout employée par les musiciens de Flamenco, cette guitare ressemble à une guitare classique (et en a les principales caractéristiques), mais est plus fine et légèrement plus petite.
En savoir plus : sur tabs4acoustic.com`,308.99,3,9),
       (5,`JPG`,`steinway`,`Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit`,28000.00,1,17),
       (6,`JPG`,`yamaha`,`Le GC 1 est un très bon instrument.
Il possède un mécanisme précis et joliment nuancé qui n''est ni trop fluide ni trop difficile à régler. Le son est très pur et défin`,16000.00,4,),
       (7,`JPG`,`Epiphone`,`Inspirée par le Gibson SG de 1961, la guitare électrique SG Standard ''61 est dotée d''un corps classique en acajou, dans une finition Vintage Cherry et est alimentée par des humbuckers ProBucker™, avec l''électronique CTS`,429.99,3,10),
       (8,`JPG`,`Alto`,`L''enceinte SLT TS215S est une enceinte sono actives de 15 pouces et d''une puissance de 625 watts.La nouvelle gamme de subwoofers actifs Truesonic V2`,14900.00,5,13),
       (9,`JPG`,`Pearl`,`loren melato srrarra tocu tocu`,420.99,1,15),
       (10,`JPG`,`Paul`,`lomate lolo riimater toppama`,7600.99,2,23),







